### ISSUE TITLE
Imperial flags used for some languages

### ISSUE THREAD

**Issue by jonorthwash** [UniversalDependencies/universaldependencies.github.io#1]
Kurdish and Uyghur UD Treebanks are displayed using the imperial Turkish and PRC flags, respectively.    At least in the case of Uyghur, there is a more appropriate flag available.

However, this raises the question of [why flags are being used to represent languages](http://www.flagsarenotlanguages.com/blog/) at all.  Might it be more appropriate to use something else, e.g. appropriately localised names of the languages, a globe centered on a major area where the language is used, or something else?

**Comment by vinbo8** [comment]
+1, I also foresee similar issues in the future when/if languages like Kashmiri or Bengali develop their own treebanks. Not all minority/shared languages or languages in conflict zones even have associated flags - it might be a better idea to replace them with ISO codes?

**Comment by dan-zeman** [comment]
We have had a long discussion about flags before introducing them on the website and we are well aware of all the problems associated with mapping languages to flags. However, they visually improve (OK, that is a matter of taste) the page both as quick visual attactors and as decoration. They were never meant as perfect representatives of the languages; for that we use the ISO codes.

Specifically for Uyghur, we respect the preference of the people who generously provided the data (and who live in PRC).

**Comment by jonorthwash** [comment]
I'm glad it was discussed, but I worry that flag choices immediately and inherently put UD on a particular side of any number of political issues.  It's likely to cause issues in the future, as @vinit-ivar suggests, and has the potential to alienate a lot of people.  My feeling is that UD is not a political enterprise, and so should not tie down each language it supports in a political way with the expression of political sympathies, whether intended or not.

As a side note, I believe that the contributors of the Uyghur data, whatever preference they may have had themselves, likely had no choice but to ask for the PRC flag.  So UD unintentionally(?) put them in an uncomfortable situation regarding their political expression.

**Comment by dan-zeman** [comment]
So believe I and that was why I asked about the preferences. I know there is a flag associated more directly with Uyghurs, although not official. Agreed that situation of various ethnic groups is less than comfortable but it is not UD who generates the discomfort. But I do not want to discuss that here because I absolutely agree that UD is not about _political_ preferences, and that was not the purpose of the flags.

**Comment by jonorthwash** [comment]
> UD is not about _political_ preferences

Then UD should avoid the use of flags.  It's that simple.

> that was not the purpose of the flags.

If UD continues to use flags, it will get into more and more of these uncomfortable situations, as it appears to be taking sides on political issues.  Perhaps for now a disclaimer on the website would be a good idea, something like: "We don't mean anything by the flags, they're just there to look nice."  However, flags do not become apolitical just because UD wants them to be.

**Comment by jnivre** [comment]
As Dan already explained, we had long discussions about this in the past and in the end settled for flags despite the obvious arguments against them. One possibility would be to make flags optional (or have a neutral UD flag for those who do not want to have a national flag associated with their treebank/language). As a quick fix, I think a disclaimer is a good idea. How about something like:

Disclaimer: Our use of flags to symbolise languages is only intended as a visual enhancement of the website and should not be interpreted as a political statement in any way.

We could add: "We are aware that this can be problematic, and invite comments and suggestions in controversial cases." But I am afraid this might do more harm than good. Opinions?

**Comment by dan-zeman** [comment]
Agreed on both accounts. (And I believe some comments in controversial cases will come even if we do not invite them explicitly :-))

**Comment by dan-zeman** [comment]
Disclaimer added.
